export const PUT_CURRENT_WEATHER = "PUT_CURRENT_WEATHER";
export const GET_CITY = "GET_CITY";
export const GET_GEOLOCATION = "GET_GEOLOCATION";
export const PUT_HOURLY_WEATHER = "PUT_HOURLY_WEATHER";
