export const LOAD_GLOBAL_COVID = "LOAD_GLOBAL_COVID";
export const PUT_GLOBAL_COVID = "PUT_GLOBAL_COVID";

export const LOAD_DAILY_COVID = "LOAD_DAILY_COVID";
export const PUT_DAILY_COVID = "PUT_DAILY_COVID";
